typedef enum {
    FSA8S_CHANNEL_VALUES_1 = 1,                       /* 2; Radio Control; Movement;      Roll            (CH01); [-] */
    FSA8S_CHANNEL_VALUES_2 = 2,                       /* 2; Radio Control; Movement;      Pitch           (CH02); [-] */
    FSA8S_CHANNEL_VALUES_3 = 3,                       /* 2; Radio Control; Movement;      Throttle        (CH03); [-] */
    FSA8S_CHANNEL_VALUES_4 = 4,                       /* 2; Radio Control; Movement;      Yaw             (CH04); [-] */
    FSA8S_CHANNEL_VALUES_5 = 5,                       /* 2; Radio Control; TBD;           not_defined     (CH05); [-] */
    FSA8S_CHANNEL_VALUES_6 = 6,                       /* 2; Radio Control; Movement;      ESCs On/Off     (CH06); [-] */
    FSA8S_CHANNEL_VALUES_7 = 7,                       /* 2; Radio Control; TBD;           not_defined     (CH07); [-] */
    FSA8S_CHANNEL_VALUES_8 = 8,                       /* 2; Radio Control; Flight Lights; Speed           (CH08); [-] */
    FSA8S_CHANNEL_VALUES_9 = 9,                       /* 2; Radio Control; Flight Lights; Type            (CH09); [-] */
    FSA8S_CHANNEL_VALUES_10 = 10,                     /* 2; Radio Control; Flight Lights; On/Off          (CH10); [-] */
    GY87_GYRO_CALIBRATION_VALUES_ROT_RATE_ROLL = 11,  /* 3; IMU; Gyroscope;     Rotation Rate Roll  Calibration;   [°/s] */
    GY87_GYRO_CALIBRATION_VALUES_ROT_RATE_PITCH = 12, /* 3; IMU; Gyroscope;     Rotation Rate Pitch Calibration;   [°/s] */
    GY87_GYRO_CALIBRATION_VALUES_ROT_RATE_YAW = 13,   /* 3; IMU; Gyroscope;     Rotation Rate Yaw   Calibration;   [°/s] */
    GY87_ACC_CALIBRATION_VALUES_LINEAR_X = 14,        /* 3; IMU; Accelerometer; Linear Acceleration X Calibration; [g] */
    GY87_ACC_CALIBRATION_VALUES_LINEAR_Y = 15,        /* 3; IMU; Accelerometer; Linear Acceleration Y Calibration; [g] */
    GY87_ACC_CALIBRATION_VALUES_LINEAR_Z = 16,        /* 3; IMU; Accelerometer; Linear Acceleration Z Calibration; [g] */
    GY87_GYRO_VALUES_ROT_RATE_ROLL = 17,              /* 3; IMU; Gyroscope;     Rotation Rate Roll;                [°/s] */
    GY87_GYRO_VALUES_ROT_RATE_PITCH = 18,             /* 3; IMU; Gyroscope;     Rotation Rate Pitch;               [°/s] */
    GY87_GYRO_VALUES_ROT_RATE_YAW = 19,               /* 3; IMU; Gyroscope;     Rotation Rate Yaw;                 [°/s] */
    GY87_ACC_VALUES_LINEAR_X = 20,                    /* 3; IMU; Accelerometer; Linear Acceleration X;             [g] */
    GY87_ACC_VALUES_LINEAR_Y = 21,                    /* 3; IMU; Accelerometer; Linear Acceleration Y;             [g] */
    GY87_ACC_VALUES_LINEAR_Z = 22,                    /* 3; IMU; Accelerometer; Linear Acceleration Z;             [g] */
    GY87_ACC_VALUES_ANGLE_ROLL = 23,                  /* 3; IMU; Accelerometer; Rotation Angle Roll;               [°] */
    GY87_ACC_VALUES_ANGLE_PITCH = 24,                 /* 3; IMU; Accelerometer; Rotation Angle Pitch;              [°] */
    GY87_MAG_VALUES_MAG_FIELD_X = 25,                 /* 3; IMU; Magnetometer;  Magnetic Field X;                  [G] */
    GY87_MAG_VALUES_MAG_FIELD_Y = 26,                 /* 3; IMU; Magnetometer;  Magnetic Field Y;                  [G] */
    GY87_MAG_VALUES_MAG_FIELD_Z = 27,                 /* 3; IMU; Magnetometer;  Magnetic Field Z;                  [G] */
    GY87_MAG_HEADING = 28,                            /* 3; IMU; Magnetometer;  Magnetic Heading;                  [°] */
    GY87_TEMPERATURE = 29,                            /* 1; General; Flight Controller; Temperature;   [°C] */
    FLIGHT_CONTROLLER_BATTERY_LEVEL = 30,             /* 1; General; Flight Controller; Battery Level; [V] */
    ESC_1 = 31,                                       /* 4; ESCs; ESC; Motor 1; [-] */
    ESC_2 = 32,                                       /* 4; ESCs; ESC; Motor 2; [-] */
    ESC_3 = 33,                                       /* 4; ESCs; ESC; Motor 3; [-] */
    ESC_4 = 34,                                       /* 4; ESCs; ESC; Motor 4; [-] */
    DESIRED_VALUE_ROLL_ANGLE = 35,                    /* 10; TABLE_NAME; ; ; [] */
    DESIRED_VALUE_PITCH_ANGLE = 36,                   /* 10; TABLE_NAME; ; ; [] */
    KALMAN_ANGLE_ROLL = 37,                           /* 5; Control System; Kalman; Roll  Angle; [°] */
    KALMAN_ANGLE_PITCH = 38,                          /* 5; Control System; Kalman; Pitch Angle; [°] */
    ERROR_VALUE_ROLL_ANGLE = 39,                      /* 10; TABLE_NAME; ; ; [] */
    ERROR_VALUE_PITCH_ANGLE = 40,                     /* 10; TABLE_NAME; ; ; [] */
    KP_ROLL_ANGLE = 41,                               /* 10; TABLE_NAME; ; ; [] */
    KI_ROLL_ANGLE = 42,                               /* 10; TABLE_NAME; ; ; [] */
    KD_ROLL_ANGLE = 43,                               /* 10; TABLE_NAME; ; ; [] */
    KP_PITCH_ANGLE = 44,                              /* 10; TABLE_NAME; ; ; [] */
    KI_PITCH_ANGLE = 45,                              /* 10; TABLE_NAME; ; ; [] */
    KD_PITCH_ANGLE = 46,                              /* 10; TABLE_NAME; ; ; [] */
    PID_OUTPUT_VALUE_ROLL_ANGLE = 47,                 /* 10; TABLE_NAME; ; ; [] */
    PID_OUTPUT_VALUE_PITCH_ANGLE = 48,                /* 10; TABLE_NAME; ; ; [] */
    DESIRED_VALUE_ROLL_RATE = 49,                     /* 10; TABLE_NAME; ; ; [] */
    DESIRED_VALUE_PITCH_RATE = 50,                    /* 10; TABLE_NAME; ; ; [] */
    DESIRED_VALUE_YAW_RATE = 51,                      /* 10; TABLE_NAME; ; ; [] */
    ERROR_VALUE_ROLL_RATE = 52,                       /* 10; TABLE_NAME; ; ; [] */
    ERROR_VALUE_PITCH_RATE = 53,                      /* 10; TABLE_NAME; ; ; [] */
    ERROR_VALUE_YAW_RATE = 54,                        /* 10; TABLE_NAME; ; ; [] */
    KP_ROLL_RATE = 55,                                /* 10; TABLE_NAME; ; ; [] */
    KI_ROLL_RATE = 56,                                /* 10; TABLE_NAME; ; ; [] */
    KD_ROLL_RATE = 57,                                /* 10; TABLE_NAME; ; ; [] */
    KP_PITCH_RATE = 58,                               /* 10; TABLE_NAME; ; ; [] */
    KI_PITCH_RATE = 59,                               /* 10; TABLE_NAME; ; ; [] */
    KP_YAW_RATE = 60,                                 /* 10; TABLE_NAME; ; ; [] */
    KI_YAW_RATE = 61,                                 /* 10; TABLE_NAME; ; ; [] */
    KD_YAW_RATE = 62,                                 /* 10; TABLE_NAME; ; ; [] */
    PID_OUTPUT_VALUE_ROLL_RATE = 63,                  /* 10; TABLE_NAME; ; ; [] */
    PID_OUTPUT_VALUE_PITCH_RATE = 64,                 /* 10; TABLE_NAME; ; ; [] */
    PID_OUTPUT_VALUE_YAW_RATE = 65,                   /* 10; TABLE_NAME; ; ; [] */
    TASK_STACK_WATERMARK_ONOFFBUTTON = 66,            /* 9; System Stack; Stack High Watermark; Task: OnOffButton      ; [words] */
    TASK_STACK_WATERMARK_CONTROLSYSTEM = 67,          /* 9; System Stack; Stack High Watermark; Task: ControlSystem    ; [words] */
    TASK_STACK_WATERMARK_USBCOMMUNICATION = 68,       /* 9; System Stack; Stack High Watermark; Task: USB_Communication; [words] */
    TASK_STACK_WATERMARK_DEBUGGING = 69,              /* 9; System Stack; Stack High Watermark; Task: Debugging        ; [words] */
    TASK_STACK_WATERMARK_BATTERYLEVEL = 70,           /* 9; System Stack; Stack High Watermark; Task: BatteryLevel     ; [words] */
    TASK_STACK_WATERMARK_BATTERYALARM = 71,           /* 9; System Stack; Stack High Watermark; Task: BatteryAlarm     ; [words] */
    TASK_STACK_WATERMARK_HEARTBEATLIGHT = 72,         /* 9; System Stack; Stack High Watermark; Task: HeartbeatLight   ; [words] */
    TASK_STACK_WATERMARK_FLIGHTLIGHTS = 73,           /* 9; System Stack; Stack High Watermark; Task: FlightLights     ; [words] */
} DebugSignalsIds_t;
