repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-merge-conflict
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.0
    hooks:
    -   id: clang-format
        args: [-style=file]
        files: ^(APIs/|Drivers/Devices/|Settings/).*\.([ch])$
